default:
  url: 'https://en.wikipedia.org/wiki/List_of_countries_by_GDP_%28nominal%29'
  log_file_path: 'generated/etl_project_log.txt'
  table_name: 'Countries_by_GDP'
  db_name: 'World_Economies.db'
  api_url: 'https://restcountries.com/v3.1/all'